### ISSUE TITLE
Create a kubernetes cluster for GCP (first iteration)

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/infra#1]
This should also include:

- [x] Step 1: Create a GKE cluster using terraform.
- [x] Step 2: Deploy the ingress nginx 
- [x] Step 3: Deploy cert-manager
- [x] Step 4: Deploy a sample application the see if cert-manager is working fine.
- [x] Step 5: Deploy Hashicorp vault to manage secrets
- [x] Step 6: Deploy nachet-backend
- [x] Step 7: Deploy finesse-backend
- [ ] Step 8: Deploy ArgoCD with Kustomize
- [ ] Step 9: Deploy kube-prometheus-stack
- [ ] Step 10: Deploy OTEL

For more information. Check the ADR at https://github.com/ai-cfia/dev-rel-docs/pull/86

**Comment by ThomasCardin** [comment]
NGINX Ingress can be found here: https://github.com/kubernetes/ingress-nginx

**Comment by rngadam** [comment]
@ThomasCardin the issue is marked as completed but the list is incomplete. 

If the last 3 remaining tasks are postponed, modify the checklist to provide pointers to the new issue to indicate the work has been postponed
