### ISSUE TITLE
As a DevOps, I would like to manage inspection.alpha.canada.ca withTerraform

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/infra#36]
## Executive summary

Manage the subdomain (inspection.alpha.canada.ca) delegated by https://github.com/cds-snc/dns using Infrastructure as Code (IaC).

## Context

Currently, applications are deployed on a third-party DNS that has no connection to the agency. The goal is to bring these services under a DNS linked to the agency while following digital standards as well as [additional instructions](https://alpha.canada.ca/en/instructions.html) for services deployed under alpha.canada.ca.

## TODO

- [ ] Open a [pull request](https://github.com/cds-snc/dns) following [this example](https://github.com/cds-snc/dns/blob/main/terraform/phac-aspc.alpha.canada.ca.tf)
- [ ] Create CNAME records
    - [ ] Finesse CNAME
    - [ ] Nachet CNAME
- [ ] Create the A record. Monitorer [this issue](https://github.com/ai-cfia/infra/issues/3) to know when the IP will be accessible
- [ ] Ensure that the sites under this subdomain comply with [alpha.canada.ca documentation](https://alpha.canada.ca/en/instructions.html)
